### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [George-u/bootstrap-template#1]
1)
от этого замечания можно избавиться?
![image](https://user-images.githubusercontent.com/8464662/145947080-d400a12b-47f8-4f42-b633-8e832a7684e8.png)

2)
В HTML5 нет такого синтаксиса, вы используете синтаксис XHTML, что противоречит инструкции DOCTYPE html.
Разберитесь в причине появление такого синтаксиса. Обычно виновником является плагин PRETTIER, неправильно установленный в качестве форматтера по умолчанию для HTML-страниц. 
С деталями вы можете ознакомиться в уроке по настройке VSCode.
Затем приведите разметку всех без исключения файлов вашего проекта к стандарту HTML5, удалив обратные слеши для всех непарных тегов.
После этого выполните автоформатирование кода для всех исправленных файлов.

![image](https://user-images.githubusercontent.com/8464662/145947183-86b5e8eb-90ae-4e3b-a187-022fbc1633a5.png)

3)
когда вы делаете проект, он должен соответствовать макету.
у вас нет соответствия ни в тексте (ладно с текстом), ни в размерах элементов
![image](https://user-images.githubusercontent.com/8464662/145947310-5a1fc73c-7ef5-42bd-adb1-cfba086aeb4e.png)

4)
здесь неправильная реализация
![image](https://user-images.githubusercontent.com/8464662/145947571-ebcc7cec-bc7d-4718-88ca-a322033b779e.png)

**Comment by George-u** [comment]
1. виправив помилку https://prnt.sc/23pi9nm 
2. видалив всі слеші в непарних тегах, дуже дякую за підказку
3. виправив неспівпадіння в розмірах елементів
4. зробив як на макеті

**Comment by Alecto** [comment]
4 - не исправлено

в шаблоне, в макете тоже не так.

**Comment by George-u** [comment]
виправив, тепер як на демо шаблоні

**Comment by George-u** [comment]
https://prnt.sc/24okqem
